config/routes.rb
Rails.application.routes.draw do
  # define routes for Primary Tech Stack
  resources :primary_tech_stacks
  # define routes for Secondary Tech Stack
  resources :secondary_tech_stacks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/primary_tech_stack.rb
# frozen_string_literal:true

class PrimaryTechStack < ApplicationRecord
  validates :stack, :skills, :generic_info, presence: true
end

app/models/secondary_tech_stack.rb
# frozen_string_literal:true

class SecondaryTechStack < ApplicationRecord
  validates :stack, :skills, :generic_info, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/primary_tech_stacks_controller.rb
# frozen_string_literal:true

class PrimaryTechStacksController < ApplicationController
  before_action :set_primary_tech_stack, only: %i[edit update show destory]

  def index
    @primary_tech_stacks = PrimaryTechStack.all
  end

  def new
    @primary_tech_stack = PrimaryTechStack.new
  end

  def create
    @primary_tech_stack = PrimaryTechStack.new(primary_tech_stack_params)
    if @primary_tech_stack.save
      flash[:notice] = 'Primary Stack created Successfully!'
      redirect_to primary_tech_stacks_path
    else
      flash[:error] = 'Create Operation has been Failed!'
      render :new
    end
  end

  def update
    if @primary_tech_stack.update(primary_tech_stack_params)
      flash[:notice] = 'PrimaryTechStack records updated Successfully!'
      redirect_to primary_tech_stack_path
    else
      flash[:error] = 'updation Operation has been Failed!'
      render :edit
    end
  end

  def edit; end

  def show; end

  def destroy
    @primary_tech_stack = PrimaryTechStack.find(params[:id])
    if @primary_tech_stack.destroy
      flash[:notice] = 'PrimaryTechStack has been Deleted!'
      redirect_to primary_tech_stacks_path
    else
      flash[:error] = 'Deletion Operation has been Failed!'
    end
  end

  private

  def set_primary_tech_stack
    @primary_tech_stack = PrimaryTechStack.find_by(id: params[:id])
  end

  def primary_tech_stack_params
    params.require(:primary_tech_stack).permit(:stack, :skills, :generic_info)
  end
end

app/controllers/secondary_tech_stacks_controller.rb
# frozen_string_literal:true

class SecondaryTechStacksController < ApplicationController
  before_action :set_secondary_tech_stack, only: %i[edit update show destory]

  def index
    @secondary_tech_stacks = SecondaryTechStack.all
  end

  def new
    @secondary_tech_stack = SecondaryTechStack.new
  end

  def create
    @secondary_tech_stack = SecondaryTechStack.new(secondary_tech_stack_params)
    if @secondary_tech_stack.save
      flash[:notice] = 'Secondary Stack created Successfully!'
      redirect_to secondary_tech_stacks_path
    else
      flash[:error] = 'Create Operation has been Failed!'
      render :new
    end
  end

  def update
    if @secondary_tech_stack.update(secondary_tech_stack_params)
      flash[:notice] = 'Secondary Stack records updated Successfully!'
      redirect_to secondary_tech_stack_path
    else
      flash[:error] = 'updation Operation has been Failed!'
      render :edit
    end
  end

  def edit; end

  def show; end

  def destroy
    @secondary_tech_stack = SecondaryTechStack.find(params[:id])
    if @secondary_tech_stack.destroy
      flash[:notice] = 'SecondaryTechStack has been Deleted!'
      redirect_to secondary_tech_stacks_path
    else
      flash[:error] = 'Deletion Operation has been Failed!'
    end
  end

  private

  def set_secondary_tech_stack
    @secondary_tech_stack = SecondaryTechStack.find_by(id: params[:id])
  end

  def secondary_tech_stack_params
    params.require(:secondary_tech_stack).permit(:stack, :skills, :generic_info)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/primary_tech_stacks_helper.rb
module PrimaryTechStacksHelper
end

app/helpers/secondary_tech_stacks_helper.rb
module SecondaryTechStacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoWebApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/primary_tech_stacks/_form.html.erb
<% if @primary_tech_stack.errors.any? %>
  <h4> The following errors prevented the primary stack details from being saved ! </h4>
  <ul>
    <% @primary_tech_stack.errors.full_messages.each do |msg| %>
      <li class = "text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model:@primary_tech_stack, local: true, data: {turbo: false}) do |f| %>
  <div class = "field form-group" >
    <strong><%= f.label :stack %></strong>
    <%= f.text_field :stack, class:"form-control" %>
  </div><br>
  
  <div class = "field form-group" >
    <strong><%= f.label :skills %></strong>
    <%= f.text_field :skills, class:"form-control" %>
  </div><br>

  <div class = "field form-group" >
    <strong><%= f.label :generic_info %></strong>
    <%= f.text_field :generic_info, class:"form-control" %>
  </div><br>

  <div class="text-center">
    <div class = "action" >
      <%= f.submit "Create Primary Stack", class:"btn btn-success" %>
    </div>
  </div><br>

  <div class="text-center">
    <div class = "field form-group" >
      <%= link_to 'Dismiss', { controller: 'primary_tech_stacks', action: 'index'}, class: "btn btn-danger" %>
    </div>
  </div>
<% end %>

app/views/primary_tech_stacks/edit.html.erb
<h2 class = "text-center mt-4" >Edit Primary Stack</h2><br>

<%= render 'form' %>

app/views/primary_tech_stacks/index.html.erb
<h2 class = "text-center mt-4" >List of Primary Stacks</h2><br>
<%= link_to "Add New", new_primary_tech_stack_path, class:"btn btn-secondary" %><br><br>

<table class = "table table-bordered">
  <thead class = "table-light text-center">
    <tr>
      <th> Stack </th>
      <th> Skills </th>
      <th> Generic Info </th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody class = "text-center">
    <% @primary_tech_stacks.each do |primary| %>
      <tr>
        <td><%= primary.stack %></td>
        <td><%= primary.skills %></td>
        <td><%= primary.generic_info %></td>
        <div>
          <td>
            <div class="btn-group" role="group">
              <%= link_to 'Show', primary_tech_stack_path(primary), class: "text-decoration-none btn btn-info" %>
              <%= link_to 'Edit', edit_primary_tech_stack_path(primary), class: "text-decoration-none btn btn-dark" %>
              <%= button_to 'Delete', primary_tech_stack_path(primary), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %>
            </div>
          </td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/primary_tech_stacks/new.html.erb
<h2 class = "text-center mt-4" >Add New Primary Stack</h2><br>

<%= render 'form' %>

app/views/primary_tech_stacks/show.html.erb
<h2 class="text-center mt-4">Primary Stack</h2><hr>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 mt-4">
      <div class=" text-center mb-5">
        <p class="card-title"><strong>Stack : </strong><%= @primary_tech_stack.stack %><p>
        <p class="card-title"><strong>Skills : </strong><%= @primary_tech_stack.skills %><p>
        <p class="card-text"><strong>Generic Information : </strong><%= @primary_tech_stack.generic_info %></p><br>
        <p class="card-text"><%= link_to 'Edit', edit_primary_tech_stack_path(@primary_tech_stack), class: "text-decoration-none btn btn-dark" %></p>
        <p class="card-text"><%= button_to 'Delete', primary_tech_stack_path(@primary_tech_stack), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %></p>
        <p class="card-text"> <%= link_to 'Back', { controller: 'primary_tech_stacks', action: 'index'}, class: "btn btn-primary" %> </p>
      </div>
    </div>
  </div>
</div>

app/views/secondary_tech_stacks/_form.html.erb
<% if @secondary_tech_stack.errors.any? %>
  <h4> The following errors prevented the secondary stack details from being saved ! </h4>
  <ul>
    <% @secondary_tech_stack.errors.full_messages.each do |msg| %>
      <li class = "text-danger"> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model:@secondary_tech_stack, local: true, data: {turbo: false}) do |f| %>
  <div class = "field form-group" >
    <strong><%= f.label :stack %></strong>
    <%= f.text_field :stack, class:"form-control" %>
  </div><br>
  
  <div class = "field form-group" >
    <strong><%= f.label :skills %></strong>
    <%= f.text_field :skills, class:"form-control" %>
  </div><br>

  <div class = "field form-group" >
    <strong><%= f.label :generic_info %></strong>
    <%= f.text_field :generic_info, class:"form-control" %>
  </div><br>

  <div class="text-center">
    <div class = "action" >
      <%= f.submit "Create Secondary Stack", class:"btn btn-success" %>
    </div>
  </div><br>

  <div class="text-center">
    <div class = "field form-group" >
      <%= link_to 'Dismiss', { controller: 'secondary_tech_stacks', action: 'index'}, class: "btn btn-danger" %>
    </div>
  </div>
<% end %>

app/views/secondary_tech_stacks/edit.html.erb
<h2 class = "text-center mt-4" >Edit Secondary Stack</h2><br>

<%= render 'form' %>

app/views/secondary_tech_stacks/index.html.erb
<h2 class = "text-center mt-4" >List of Secondary Stacks</h2><br>
<%= link_to "Add New Secondary Stack", new_secondary_tech_stack_path, class:"btn btn-secondary" %><br><br>

<table class = "table table-bordered">
  <thead class = "table-light text-center">
    <tr>
      <th> Stack </th>
      <th> Skills </th>
      <th> Generic Info </th>
      <th> Action </th>
    </tr>
  </thead>
  <tbody class = "text-center">
    <% @secondary_tech_stacks.each do |secondary| %>
      <tr>
        <td><%= secondary.stack %></td>
        <td><%= secondary.skills %></td>
        <td><%= secondary.generic_info %></td>
        <div>
          <td>
            <div class="btn-group" role="group">
              <%= link_to 'Show', secondary_tech_stack_path(secondary), class: "text-decoration-none btn btn-info" %>
              <%= link_to 'Edit', edit_secondary_tech_stack_path(secondary), class: "text-decoration-none btn btn-dark" %>
              <%= button_to 'Delete', secondary_tech_stack_path(secondary), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %>
            </div>
          </td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/secondary_tech_stacks/new.html.erb
<h2 class = "text-center mt-4" >Add New Secondary Stack</h2><br>

<%= render 'form' %>

app/views/secondary_tech_stacks/show.html.erb
<h2 class="text-center mt-4">Secondary Stack</h2><hr>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 mt-4">
      <div class=" text-center mb-5">
        <p class="card-title"><strong>Stack : </strong><%= @secondary_tech_stack.stack %><p>
        <p class="card-title"><strong>Skills : </strong><%= @secondary_tech_stack.skills %><p>
        <p class="card-text"><strong>Generic Information : </strong><%= @secondary_tech_stack.generic_info %></p><br>
        <p class="card-text"><%= link_to 'Edit', edit_secondary_tech_stack_path(@secondary_tech_stack), class: "text-decoration-none btn btn-dark" %></p>
        <p class="card-text"><%= button_to 'Delete', secondary_tech_stack_path(@secondary_tech_stack), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %></p>
        <p class="card-text"> <%= link_to 'Back', { controller: 'secondary_tech_stacks', action: 'index'}, class: "btn btn-primary" %> </p>
      </div>
    </div>
  </div>
</div>